# fly.toml app configuration file generated for whale-redirect on 2024-05-23T19:41:33+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'whale-redirect'
primary_region = 'fra'

[mounts]
source = 'data'
destination = '/data'

[http_service]
force_https = true
internal_port = 3000
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[http_service.checks]]
interval = "30s"
grace_period = "7s"
method = "get"
path = "/_healthcheck"
protocol = "http"
timeout = "5s"
tls_skip_verify = false

[[vm]]
size = 'shared-cpu-1x'

[env]
NODE_ENV = 'production'
